Prabin_SMS.web/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration.UserSecrets;
using Prabin_SMS.Infrastructure.IRepository;
using Prabin_SMS.Models.Entity;
using Prabin_SMS.web.Models;

namespace Prabin_SMS.web.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly ICRUDServices<Course> _course;
        private readonly ICRUDServices<Student> _student;
        private readonly ICRUDServices<Degree> _degree;
        private readonly UserManager<ApplicationUser> _user;

        public CourseController(ICRUDServices<Course> course, ICRUDServices<Student> student, UserManager<ApplicationUser> user, ICRUDServices<Degree> degree)
        {
            _course = course;
            _student = student;
            _user = user;
            _degree = degree;
        }

        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("ADMIN"))
            {
               var course = await _course.GetAllAsync();
                return View(course);
            }
            else
            {
                var course = await _course.GetAllAsync(p=>p.IsActive);
                return View(course);
            }
            
        }
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> AddEdit(int id)
        {
            Course course = new Course();
            if (id != 0)
            {
               course =  await _course.GetAsync(id);
            }
            return View(course);

        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(Course course)
        {
            if (ModelState.IsValid)
            {
                var UserId = _user.GetUserId(HttpContext.User);
                if (course.Id == 0)
                {
                    course.CreatedBy = UserId;
                    course.CreatedDate = DateTime.Now;
                    await _course.InsertAsync(course);
                }
                else if (course.Id != 0)
                {
                    Course updated_course = await _course.GetAsync(course.Id);
                    updated_course.IsActive = course.IsActive;
                    updated_course.CourseName = course.CourseName;
                    updated_course.CourseDescription = course.CourseDescription;
                    updated_course.CreditHours = course.CreditHours;
                    updated_course.FullMarks = course.FullMarks;
                    updated_course.ModifiedDate = DateTime.Now;
                    updated_course.ModifiedBy = UserId;
                    await _course.UpdateAsync(updated_course);
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(AddEdit));

        }


    }
}

Prabin_SMS.web/Controllers/DegreeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration.UserSecrets;
using Prabin_SMS.Infrastructure.IRepository;
using Prabin_SMS.Models.Entity;
using Prabin_SMS.Models.ViewModels;
using Prabin_SMS.web.Models;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.Data.SqlClient;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.IdentityModel.Tokens;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Prabin_SMS.web.Controllers
{
    public class DegreeController : Controller
    {

        private readonly ICRUDServices<Course> _course;
        private readonly ICRUDServices<Student> _student;
        private readonly ICRUDServices<Degree> _degree;
        private readonly ICRUDServices<Discipline> _discipline;
        private readonly UserManager<ApplicationUser> _user;
        private readonly ICRUDServices<DegreeCourse> _DegreeCourse;
        private readonly IRawSqlRepository rawSqlRepository;

        public DegreeController(ICRUDServices<Course> course, ICRUDServices<Student> student, UserManager<ApplicationUser> user, ICRUDServices<Degree> degree, ICRUDServices<Discipline> discipline, ICRUDServices<DegreeCourse> degreeCourse, IRawSqlRepository rawSqlRepository)
        {
            _course = course;
            _student = student;
            _user = user;
            _degree = degree;
            _discipline = discipline;
            _DegreeCourse = degreeCourse;
            this.rawSqlRepository = rawSqlRepository;
        }

        public async Task<IActionResult> Index(DegreeViewModel degreeViewModel)
        {
            ViewBag.Discipline = await _discipline.GetAllAsync();
            ViewBag.Course = await _course.GetAllAsync();
            if (degreeViewModel.Degree.IsNullOrEmpty())
            {
                if (User.IsInRole("ADMIN"))
                {
                    degreeViewModel.Degree = await _degree.GetAllAsync();
                }
                else
                {
                    degreeViewModel.Degree = await _degree.GetAllAsync(p => p.IsActive);
                }
            }
            return View(degreeViewModel);
        }

        public async Task<IActionResult> Search(DegreeViewModel degreeViewModel)
        {
            ViewBag.Discipline = await _discipline.GetAllAsync();
            ViewBag.Course = await _course.GetAllAsync();

            var result = rawSqlRepository.FromSql<Degree>("usp_getDegree @courseId, @disciplineId, @level, @startDate, @query",
              new SqlParameter("@courseId", degreeViewModel.degreeSearchViewModel.CourseId == 0 ? (object)DBNull.Value : degreeViewModel.degreeSearchViewModel.CourseId),
              new SqlParameter("@disciplineId", degreeViewModel.degreeSearchViewModel.DisciplineId == 0 ? (object)DBNull.Value : degreeViewModel.degreeSearchViewModel.DisciplineId),
              new SqlParameter("@level", degreeViewModel.degreeSearchViewModel.Level == null ? (object)DBNull.Value : degreeViewModel.degreeSearchViewModel.Level),
              new SqlParameter("@startDate", degreeViewModel.degreeSearchViewModel.StartDate == null ? (object)DBNull.Value : degreeViewModel.degreeSearchViewModel.StartDate),
              new SqlParameter("@query", degreeViewModel.degreeSearchViewModel.Query == null ? (object)DBNull.Value : degreeViewModel.degreeSearchViewModel.Query)
              ).ToList();

            degreeViewModel.Degree = result;

            return View(nameof(Index), degreeViewModel);

        }

        [Authorize]
        public async Task<IActionResult> AddEdit(int id)
        {
            ViewBag.Discipline = await _discipline.GetAllAsync();
            Degree degree = new Degree();
            if (id != 0)
            {
                degree = await _degree.GetAsync(id);
            }
            return View(degree);

        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(Degree degree)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Discipline = await _discipline.GetAllAsync();
                var UserId = _user.GetUserId(HttpContext.User);
                if (degree.Id == 0)
                {
                    degree.CreatedBy = UserId;
                    degree.CreatedDate = DateTime.Now;
                    await _degree.InsertAsync(degree);
                }
                else if (degree.Id != 0)
                {
                    Degree updated_degree = await _degree.GetAsync(degree.Id);
                    updated_degree.IsActive = degree.IsActive;
                    updated_degree.StartDate = degree.StartDate;
                    updated_degree.DegreeName = degree.DegreeName;
                    updated_degree.DegreeDescription = degree.DegreeDescription;
                    updated_degree.DisciplineId = degree.DisciplineId;
                    updated_degree.Academic_Level = degree.Academic_Level;
                    updated_degree.No_Of_Semesters = degree.No_Of_Semesters;
                    updated_degree.No_Of_Years = degree.No_Of_Years;
                    updated_degree.TotalSeats = degree.TotalSeats;
                    updated_degree.ModifiedDate = DateTime.Now;
                    updated_degree.ModifiedBy = UserId;
                    await _degree.UpdateAsync(updated_degree);
                }
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(AddEdit));

        }

        [HttpGet]
        [Route("api/Degree/getAllCourses")]
        public async Task<IActionResult> getAllCourses(string query)
        {
            query = Regex.Escape(query);
            CourseSearchViewModel courseSearchViewModel = new CourseSearchViewModel();
            try
            {
                var courses = await _course.GetAllAsync();

                // In-memory filtering using Regex
                var filteredCourses = courses
                    .Where(p => Regex.IsMatch(p.CourseName, "^" + Regex.Escape(query) + ".*$", RegexOptions.IgnoreCase))
                    .ToList();
                courseSearchViewModel.Courses = filteredCourses;
            }
            catch (Exception ex)
            {

            }
            return Json(new { courseSearchViewModel.Courses });
        }

        [HttpPost]
        [Route("api/Degree/getSemesterCourses")]
        public async Task<IActionResult> getSemesterCourses(CourseSearchViewModel courseSearchViewModel)
        {
            try
            {
                var courseList = new List<CourseResultViewModel>();
                if (courseSearchViewModel.DegreeId != 0)
                {
                    var courseIds = await _DegreeCourse.GetAllAsync(p => p.DegreeId == courseSearchViewModel.DegreeId && p.Semester == courseSearchViewModel.Semester);

                    foreach (var courseId in courseIds)
                    {
                        CourseResultViewModel courseResultViewModel = new CourseResultViewModel();
                        var course = await _course.GetAsync(p => p.Id == courseId.CourseId);
                        courseResultViewModel.Id = course.Id;
                        courseResultViewModel.CourseName = course.CourseName;
                        courseList.Add(courseResultViewModel);
                    }
                }
                return Json(new { courseList });

            }
            catch (Exception ex) { return Json(new { courseSearchViewModel.Courses }); }
        }

        [HttpPost]
        [Route("api/Degree/setCourse")]
        public async Task<IActionResult> setCourse(CourseSearchViewModel courseSearchViewModel)
        {
            DegreeCourse degreeCourse = new DegreeCourse();
            degreeCourse.CourseId = courseSearchViewModel.CourseId;
            degreeCourse.DegreeId = courseSearchViewModel.DegreeId;
            degreeCourse.Semester = courseSearchViewModel.Semester;
            var result = await _DegreeCourse.InsertAsync(degreeCourse);
            return Json(new { result });
        }

        [HttpPost]
        [Route("api/Degree/DeleteCourse")]
        public async Task<IActionResult> DeleteCourse(CourseSearchViewModel courseSearchViewModel)
        {
            var degreeCourse = await _DegreeCourse.GetAsync(p => p.DegreeId == courseSearchViewModel.DegreeId && p.Semester == courseSearchViewModel.Semester && p.CourseId == courseSearchViewModel.CourseId);

            var result = _DegreeCourse.Delete(degreeCourse);
            return Json(new { result });
        }

        [HttpGet]
        [Route("api/Degree/getRemainingSeats")]
        public async Task<IActionResult> getRemainingSeats(int totalCount, int degreeId)
        {
            var occupiedSeats = await _student.GetAllAsync(p => p.DegreeId == degreeId);
            var Count = occupiedSeats.Count();
            return Json(new { Count });
        }

        [HttpPost]
        [Route("api/Degree/PostStudent")]
        public async Task<IActionResult> PostStudent(Student studentData)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var UserId = _user.GetUserId(HttpContext.User);
                    var user = await _user.FindByIdAsync(UserId);

                    if (studentData.studentPhoto != null)
                    {
                        string fileDirectory = $"wwwroot/StudentImage";

                        if (!Directory.Exists(fileDirectory))
                        {
                            Directory.CreateDirectory(fileDirectory);
                        }
                        string uniqueFileName = Guid.NewGuid() + "_" + studentData.studentPhoto.FileName;

Prabin_SMS.web/Controllers/DisciplineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration.UserSecrets;
using Prabin_SMS.Infrastructure.IRepository;
using Prabin_SMS.Models.Entity;
using Prabin_SMS.web.Models;

namespace Prabin_SMS.web.Controllers
{
    [Authorize]
    public class DisciplineController : Controller
    {
        private readonly ICRUDServices<Course> _course;
        private readonly ICRUDServices<Student> _student;
        private readonly ICRUDServices<Degree> _degree;
        private readonly ICRUDServices<Discipline> _discipline;
        private readonly UserManager<ApplicationUser> _user;

        public DisciplineController(ICRUDServices<Course> course, ICRUDServices<Student> student, UserManager<ApplicationUser> user, ICRUDServices<Degree> degree, ICRUDServices<Discipline> discipline)
        {
            _course = course;
            _student = student;
            _user = user;
            _degree = degree;
            _discipline = discipline;
        }

        public async Task<IActionResult> Index()
        {
            var discipline =await _discipline.GetAllAsync();
            return View(discipline);
        }


        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> AddEdit(int id)
        {
            Discipline discipline = new Discipline();
            if (id != 0)
            {
               discipline =  await _discipline.GetAsync(id);
            }
            return View(discipline);

        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(Discipline discipline)
        {
            if (ModelState.IsValid)
            {
                var UserId = _user.GetUserId(HttpContext.User);
                if (discipline.Id == 0)
                {
                    discipline.CreatedBy = UserId;
                    discipline.CreatedDate = DateTime.Now;
                    await _discipline.InsertAsync(discipline);
                }
                else if (discipline.Id != 0)
                {
                    Discipline updated_discipline = await _discipline.GetAsync(discipline.Id);
                    updated_discipline.IsActive = discipline.IsActive;
                    updated_discipline.Name = discipline.Name;
                    updated_discipline.ModifiedDate = DateTime.Now;
                    updated_discipline.ModifiedBy = UserId;
                    await _discipline.UpdateAsync(updated_discipline);
                }

                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(AddEdit));
        }


    }
}

Prabin_SMS.web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Cache-Control" content="no-store, max-age=0">
    <title>@ViewData["Title"] - Prabin_SMS.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Prabin_SMS.web.styles.css" asp-append-version="true" />
    <style>
        th{
            border-bottom:0px !important
        }

        a{
            color: #000000ad !important;
            background: transparent !important
        }

        button{
            color: #000000ad !important;
            background: transparent !important
        }

        td{
            border-bottom: 2px solid #635252 !important;
            text-align: center
        }

        .buttontable{
            margin-top: -6px !important;
            border-radius: 10px !important;
            line-height: 20px !important;
        }

        input[type="range"]::-webkit-slider-runnable-track {
            background: #e5d1d1;
        }

        input[type='range']::-webkit-slider-thumb {
            background: #c9abab;
        }

        input{
            background: transparent !important ;
            color: #767272;
        }

        select{
            background: transparent !important
        }
        
        .addEditInput {
            color: #767272;
            border-bottom: 1px solid !important;
            border: 0px;
        }

        .addEditModalImage{
            background: #b7b7b7;
            border: 1px solid #f5f0db;
            height: 145px !important;
            width: 145px !important;
            border-radius: 10%;
        }

        .ball{
            background: #767272;
            height: 10px;
            width:10px
        }

        .addEditImage{
            background:#b7b7b7;
            border: 1px solid #f5f0db;
        }

        .addEditImgUser{
            background: #b7b7b7;
            border-radius:50%

        }

        label{
            color: #605050
        }
    </style>

</head>
<body style="background: #f3efd7; font-family: cursive;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light mb-3" >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Degree" asp-action="Index" style="color: #000000ad !important">Prabin_SMS.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                        
                        
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">DashBoard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Degree" asp-action="Index">Degree</a>
                            </li>
                        
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Discipline" asp-action="Index">Discipline</a>
                            </li>
                        }
                    </ul>
                    @if (User.IsInRole("SUPERADMIN"))
                    {
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                    }
                    <partial name="_LoginPartial"></partial>
                </div>
               
                

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>